variables:
  GIT_SUBMODULE_STRATEGY: recursive
stages:
  - build

job:
  stage: build
  image: python:3.11
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"'
    - nvm install 16
    - nvm use 16
    - npm install -g zx
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - npm install
    - mkdir out
    - zx ./quick_comparison.mjs
  artifacts:
    paths:
      - out/
    expire_in: 1 week
    when: always
